In [7]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_wine
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

In [3]:
wine = load_wine()
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [6]:
df = pd.DataFrame(wine.data,columns = wine.feature_names)
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [9]:
df['target'] = wine.target
df.head(10)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
5,14.20,1.76,2.45,15.2,112.0,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450.0,0
6,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0,0
7,14.06,2.15,2.61,17.6,121.0,2.60,2.51,0.31,1.25,5.05,1.06,3.58,1295.0,0
8,14.83,1.64,2.17,14.0,97.0,2.80,2.98,0.29,1.98,5.20,1.08,2.85,1045.0,0
9,13.86,1.35,2.27,16.0,98.0,2.98,3.15,0.22,1.85,7.22,1.01,3.55,1045.0,0

In [17]:
scaler = MinMaxScaler()
def scaled(feature):
    df[feature] = scaler.fit_transform(df[[feature]])
scaled('alcohol')
scaled('ash')
scaled('total_phenols')
scaled('flavanoids')
scaled('color_intensity')
scaled('od280/od315_of_diluted_wines')
df = df.drop(['proline', 'magnesium'], axis='columns')
df.head(10)

,alcohol,malic_acid,ash,alcalinity_of_ash,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,target
0,0.842105,1.71,0.572193,15.6,0.627586,0.573840,0.28,2.29,0.372014,1.04,0.970696,0
1,0.571053,1.78,0.417112,11.2,0.575862,0.510549,0.26,1.28,0.264505,1.05,0.780220,0
2,0.560526,2.36,0.700535,18.6,0.627586,0.611814,0.30,2.81,0.375427,1.03,0.695971,0
3,0.878947,1.95,0.609626,16.8,0.989655,0.664557,0.24,2.18,0.556314,0.86,0.798535,0
4,0.581579,2.59,0.807487,21.0,0.627586,0.495781,0.39,1.82,0.259386,1.04,0.608059,0
5,0.834211,1.76,0.582888,15.2,0.789655,0.643460,0.34,1.97,0.466724,1.05,0.578755,0
6,0.884211,1.87,0.582888,14.6,0.524138,0.459916,0.30,1.98,0.338737,1.02,0.846154,0
7,0.797368,2.15,0.668449,17.6,0.558621,0.457806,0.31,1.25,0.321672,1.06,0.846154,0
8,1.000000,1.64,0.433155,14.0,0.627586,0.556962,0.29,1.98,0.334471,1.08,0.578755,0
9,0.744737,1.35,0.486631,16.0,0.689655,0.592827,0.22,1.85,0.506826,1.01,0.835165,0

In [19]:
input = df.drop('target',axis='columns')
target = df['target']
x_train,x_test,y_train,y_test = train_test_split(input,target,test_size = 0.2)

In [20]:
model1 = GaussianNB()
model1.fit(x_train,y_train)

GaussianNB()

In [22]:
model1.score(x_test,y_test)

0.9722222222222222

In [23]:
model1.score(x_train,y_train)

0.9647887323943662

In [24]:
model2 = MultinomialNB()
model2.fit(x_train,y_train)

MultinomialNB()

In [25]:
model2.score(x_test,y_test)

0.8888888888888888

In [26]:
model2.score(x_train,y_train)

0.8802816901408451